### ISSUE TITLE
JAXSA error!! (+plus)

### ISSUE THREAD

**Issue by 02-siyeong** [FORMAS/OWL-S-Composer#3]
I don't Know why the problem appear!

![ll](https://cloud.githubusercontent.com/assets/13284388/9003526/c9cae55e-37a9-11e5-8bd8-c5d4d96e352b.png)

**Comment by efraimmachado** [comment]
In this case, the plugin didn't find the the wsdl file because the wsdl's url is not accessible. Please, check your tomcat's address and make sure that the wsdl file path is right.

**Comment by 02-siyeong** [comment]
Thank you for your response.
and, please be good to understand my awkward English.

I don't understand the sentence "wsdl's url is not accessible" means.

why wsdl's url is not accessible?
After typing "http://localhost:8080/godpa/services/Godpa?wsdl", work normally in picture above.

is the way to set preference my tomcat path?

ps1. my tomcat and axis2 work nomarly.
ps2. I am imitating tutorial video in Youtube and your pdf file.

**Comment by dussebr** [comment]
Profa Daniela UFBA, said that the Owls API is offline. For some unknown reason the research group that maintained this API let it offline. The OWL-S-Composer uses JAXSA that uses the Owls API that's why it stopped working.
